## Importing Libraries

In [1]:
import torch
import numpy as np

## Converting Normal NumPy Array to PyTorch Tensor

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
arr.dtype

dtype('int32')

In [4]:
type(arr)

numpy.ndarray

### Specific Way

In [5]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [6]:
type(x)

torch.Tensor

### Generalized Way

In [7]:
x = torch.as_tensor(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [8]:
type(x)

torch.Tensor

### 2D NumPy Array

In [9]:
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
x2d = torch.from_numpy(arr2d)
print(x2d)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


## Direct Link between NumPy Array and PyTorch Tensor

In [12]:
arr

array([1, 2, 3, 4, 5])

In [13]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [14]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [15]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

**We do not want to create direct link**

### Solution

In [16]:
my_arr = np.arange(0, 10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [18]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [19]:
my_arr[0] = 9999
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [20]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       dtype=torch.int32)

In [21]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

## Difference between tensor and Tensor

In [22]:
my_arr = np.arange(0, 4)
my_arr

array([0, 1, 2, 3])

In [23]:
my_arr.dtype

dtype('int32')

In [24]:
torch.tensor(my_arr)

tensor([0, 1, 2, 3], dtype=torch.int32)

In [25]:
torch.Tensor(my_arr)

tensor([0., 1., 2., 3.])

## Creating Tensors from Scratch

In [26]:
torch.empty(2, 2)

tensor([[-9.6530e+01,  1.7362e-42],
        [ 0.0000e+00,  0.0000e+00]])

In [27]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [28]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [30]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [31]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [32]:
torch.rand(4, 3)

tensor([[0.2264, 0.1922, 0.2806],
        [0.4691, 0.8106, 0.0733],
        [0.2508, 0.1249, 0.1914],
        [0.6365, 0.5716, 0.8844]])

In [33]:
torch.randn(4, 3)

tensor([[ 0.9259, -0.6738,  0.2014],
        [-0.5923,  0.5064, -0.7444],
        [-0.4175,  0.8919,  1.5811],
        [ 1.2845,  1.1820, -0.0671]])

In [34]:
torch.randint(low=0, high=10, size=(5, 5))

tensor([[8, 3, 6, 4, 9],
        [6, 8, 9, 8, 8],
        [3, 3, 5, 4, 4],
        [4, 2, 3, 0, 7],
        [2, 6, 3, 2, 5]])

### Random Numbers Tensor follows an Input Size

In [35]:
x = torch.zeros(2, 5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
x.shape

torch.Size([2, 5])

In [37]:
torch.rand_like(x)

tensor([[0.4273, 0.0883, 0.5109, 0.6076, 0.3723],
        [0.5192, 0.3884, 0.7054, 0.3880, 0.5805]])

In [38]:
torch.randn_like(x)

tensor([[ 0.6960,  0.3813,  0.8599,  0.9610, -0.4150],
        [-0.1157, -0.0315, -0.7413, -0.6704,  0.0958]])

In [39]:
torch.randint_like(input=x, low=0, high=10)

tensor([[3., 0., 5., 4., 9.],
        [3., 7., 8., 1., 9.]])

### Random Seed

In [40]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [41]:
torch.rand(2, 3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [42]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## Changing Tensor Data Type

In [43]:
my_tensor = torch.tensor([1, 2, 3])
my_tensor.dtype

torch.int64

In [44]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32