## Import Libraries

In [1]:
import torch
import numpy as np

## Creating Tensor

In [2]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Indexing

In [3]:
x[1, 1]

tensor(3)

### Grapping Slices

In [4]:
x[:, 1]

tensor([1, 3, 5])

In [5]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

### View

In [6]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape

In [9]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## View Reflect the Most Current Data

In [12]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x.shape

torch.Size([10])

In [14]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
z = x.view(2, 5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x[0] = 9999
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [18]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Views Can Also Infer the Correct Size

In [19]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.shape

torch.Size([10])

In [21]:
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Basic Arithmetics

In [22]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [23]:
a

tensor([1., 2., 3.])

In [24]:
b

tensor([4., 5., 6.])

In [25]:
a + b

tensor([5., 7., 9.])

In [26]:
torch.add(a, b)

tensor([5., 7., 9.])

In [27]:
torch.subtract(a, b)

tensor([-3., -3., -3.])

In [28]:
a.mul(b)

tensor([ 4., 10., 18.])

In [29]:
a

tensor([1., 2., 3.])

In [30]:
b

tensor([4., 5., 6.])

In [31]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [32]:
a

tensor([ 4., 10., 18.])

In [33]:
b

tensor([4., 5., 6.])

## Matrix Based Operations

In [34]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [35]:
a

tensor([1., 2., 3.])

In [36]:
b

tensor([4., 5., 6.])

In [37]:
a * b

tensor([ 4., 10., 18.])

### Dot Product

In [38]:
a.dot(b)

tensor(32.)

### 2D Matrix Multiplication

In [39]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [40]:
b = torch.tensor([[6, 7], [8, 9], [10, 11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [41]:
a.shape

torch.Size([2, 3])

In [42]:
b.shape

torch.Size([3, 2])

In [43]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

## Advanced Operations

### Euclidean Norm

In [44]:
x = torch.tensor([2., 3., 4., 5.])
x

tensor([2., 3., 4., 5.])

In [45]:
x.norm()

tensor(7.3485)

In [46]:
x.numel()

4