## Import Libraries

In [1]:
import torch

## Creating Tensor

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
x

tensor(2., requires_grad=True)

In [4]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [5]:
type(y)

torch.Tensor

## Back Propagation

In [6]:
y.backward()

In [7]:
x.grad

tensor(93.)

## Back Propagation on Multiple Steps

In [8]:
x = torch.tensor([
    [1., 2., 3.],
    [3., 2., 1.]],
    requires_grad=True
                 
)

In [9]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [10]:
y = 3*x + 2

In [11]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [12]:
z = 2*y**2

In [13]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [14]:
out = z.mean()
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [15]:
out.backward()

In [16]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
